// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/google/wire"
	"gorm.io/gorm"
	"projectcharter/controller"
	"projectcharter/repository"
	"projectcharter/service"
)

// Injectors from injector.go:

func InitProjectCharter(db *gorm.DB) controller.ProjectCharterController {
	projectCharterRepository := repository.NewProjectCharterRepository(db)
	projectCharterService := service.NewProjectCharterService(projectCharterRepository)
	projectCharterController := controller.NewProjectCharterController(projectCharterService)
	return projectCharterController
}

// injector.go:

var projcharterSet = wire.NewSet(repository.NewProjectCharterRepository, service.NewProjectCharterService, controller.NewProjectCharterController)
